name: Run Auto Comment Facebook

on:
  schedule:
    - cron: '0 3 * * *'  # Menjalankan setiap hari pukul 03:00 UTC

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
    
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install selenium
          pip install python-dotenv
          pip install colorama

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oE '[0-9]+.[0-9]+.[0-9]+')
          wget -N https://chromedriver.storage.googleapis.com/$CHROME_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip -d /usr/local/bin

      # Mengatur environment variable dari GitHub Secrets
      - name: Run Selenium bot with env variables
        env:
          EMAIL_FB: ${{ secrets.EMAIL_FB }}
          PASSWORD_FB: ${{ secrets.PASSWORD_FB }}
          EMAIL_ADDR: ${{ secrets.EMAIL_ADDR }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          RECEIVER: ${{ secrets.RECEIVER }}
          LINK_LOGIN: ${{ secrets.LINK_LOGIN }}
        run: python main.py
